const carDatabase = [
  {
    id: 'car1',
    make: 'Toyota',
    model: 'Camry',
    year: 2023,
    price: {
      new: 28000,
      used_1_year: 26000,
      used_3_year: 22000,
      used_5_year: 18000,
    },
    fuelType: ['Full Hybrid (HEV)', 'Gasoline'],
    bodyStyle: ['Sedan'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['25-34', '35-44', '45-54'],
      drivingExperience: ['Experienced', 'Veteran'],
    },
    locationType: ['Urban/City', 'Suburban'],
    features: ['ADAS', 'Infotainment System', 'Premium Sound'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Moderate',
    passengers: '3-4',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car2',
    make: 'Tesla',
    model: 'Model 3',
    year: 2024,
    price: {
      new: 45000,
      used_1_year: 42000,
      used_3_year: 38000,
      used_5_year: 30000,
    },
    fuelType: ['Battery Electric (BEV)'],
    bodyStyle: ['Sedan'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['25-34', '35-44'],
      drivingExperience: ['Experienced'],
    },
    locationType: ['Urban/City', 'Suburban'],
    features: ['ADAS', 'Infotainment System', 'Panoramic Sunroof'],
    performance: 'Sporty & Agile',
    cargoNeeds: 'Moderate',
    passengers: '1-2',
    annualMileage: '5,000 - 15,000 km',
  },
  {
    id: 'car3',
    make: 'Ford',
    model: 'F-150',
    year: 2023,
    price: {
      new: 40000,
      used_1_year: 37000,
      used_3_year: 32000,
      used_5_year: 25000,
    },
    fuelType: ['Gasoline'],
    bodyStyle: ['Truck'],
    demographics: {
      gender: ['Male'],
      ageGroup: ['35-44', '45-54', '55-64'],
      drivingExperience: ['Veteran'],
    },
    locationType: ['Rural', 'Mixed'],
    features: ['Towing Package', 'Large Infotainment'],
    performance: 'Rugged Off-road Capability',
    cargoNeeds: 'Significant (towing)',
    passengers: '3-4',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car4',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    price: {
      new: 29000,
      used_1_year: 27000,
      used_3_year: 23000,
      used_5_year: 19000,
    },
    fuelType: ['Plug-in Hybrid (PHEV)', 'Gasoline'],
    bodyStyle: ['SUV/Crossover'],
    demographics: {
      gender: ['Female', 'Non-binary'],
      ageGroup: ['25-34', '35-44'],
      drivingExperience: ['Experienced'],
    },
    locationType: ['Suburban', 'Urban/City'],
    features: ['Heated Seats', 'Apple CarPlay/Android Auto'],
    performance: 'Smooth & Comfortable',
    cargoNeeds: 'Moderate',
    passengers: '3-4',
    annualMileage: '5,000 - 15,000 km',
  },
  {
    id: 'car5',
    make: 'Volkswagen',
    model: 'Golf',
    year: 2022,
    price: {
      new: 25000,
      used_1_year: 23000,
      used_3_year: 19000,
      used_5_year: 15000,
    },
    fuelType: ['Gasoline'],
    bodyStyle: ['Hatchback'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['18-24', '25-34'],
      drivingExperience: ['Novice', 'Experienced'],
    },
    locationType: ['Urban/City'],
    features: ['Compact Size', 'Good Fuel Economy'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Minimal',
    passengers: '1-2',
    annualMileage: 'Under 5,000 km',
  },
  {
    id: 'car6',
    make: 'BMW',
    model: '3 Series',
    year: 2023,
    price: {
      new: 42000,
      used_1_year: 39000,
      used_3_year: 34000,
      used_5_year: 28000,
    },
    fuelType: ['Gasoline'],
    bodyStyle: ['Sedan'],
    demographics: {
      gender: ['Male', 'Female'],
      ageGroup: ['35-44', '45-54'],
      drivingExperience: ['Experienced', 'Veteran'],
    },
    locationType: ['Suburban', 'Urban/City'],
    features: ['Sport Package', 'Premium Interior'],
    performance: 'Sporty & Agile',
    cargoNeeds: 'Moderate',
    passengers: '1-2',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car7',
    make: 'Subaru',
    model: 'Outback',
    year: 2023,
    price: {
      new: 35000,
      used_1_year: 32000,
      used_3_year: 28000,
      used_5_year: 22000,
    },
    fuelType: ['Gasoline'],
    bodyStyle: ['Wagon'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['35-44', '45-54'],
      drivingExperience: ['Experienced', 'Veteran'],
    },
    locationType: ['Rural', 'Mixed'],
    features: ['AWD', 'Roof Rails'],
    performance: 'Rugged Off-road Capability',
    cargoNeeds: 'Significant',
    passengers: '3-4',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car8',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    price: {
      new: 48000,
      used_1_year: 45000,
      used_3_year: 40000,
      used_5_year: 33000,
    },
    fuelType: ['Full Hybrid (HEV)', 'Gasoline'],
    bodyStyle: ['Sedan'],
    demographics: {
      gender: ['Male', 'Female'],
      ageGroup: ['45-54', '55-64'],
      drivingExperience: ['Veteran'],
    },
    locationType: ['Suburban', 'Urban/City'],
    features: ['Luxury Interior', 'Advanced Safety'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Minimal',
    passengers: '1-2',
    annualMileage: '5,000 - 15,000 km',
  },
  {
    id: 'car9',
    make: 'Jeep',
    model: 'Wrangler',
    year: 2023,
    price: {
      new: 38000,
      used_1_year: 35000,
      used_3_year: 30000,
      used_5_year: 24000,
    },
    fuelType: ['Gasoline'],
    bodyStyle: ['SUV/Crossover'],
    demographics: {
      gender: ['Male', 'Female'],
      ageGroup: ['25-34', '35-44'],
      drivingExperience: ['Experienced'],
    },
    locationType: ['Rural', 'Mixed'],
    features: ['Off-road Package', 'Removable Top'],
    performance: 'Rugged Off-road Capability',
    cargoNeeds: 'Significant',
    passengers: '1-2',
    annualMileage: '5,000 - 15,000 km',
  },
  {
    id: 'car10',
    make: 'Honda',
    model: 'CR-V',
    year: 2023,
    price: {
      new: 32000,
      used_1_year: 30000,
      used_3_year: 26000,
      used_5_year: 20000,
    },
    fuelType: ['Full Hybrid (HEV)', 'Gasoline'],
    bodyStyle: ['SUV/Crossover'],
    demographics: {
      gender: ['Female', 'Non-binary'],
      ageGroup: ['25-34', '35-44', '45-54'],
      drivingExperience: ['Experienced'],
    },
    locationType: ['Suburban', 'Urban/City'],
    features: ['Spacious Interior', 'Reliable'],
    performance: 'Smooth & Comfortable',
    cargoNeeds: 'Moderate',
    passengers: '3-4',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car11',
    make: 'Chevrolet',
    model: 'Bolt EV',
    year: 2023,
    price: {
      new: 27000,
      used_1_year: 25000,
      used_3_year: 21000,
      used_5_year: 17000,
    },
    fuelType: ['Battery Electric (BEV)'],
    bodyStyle: ['Hatchback'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['18-24', '25-34'],
      drivingExperience: ['Novice', 'Experienced'],
    },
    locationType: ['Urban/City'],
    features: ['Long Range EV', 'Compact'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Minimal',
    passengers: '1-2',
    annualMileage: 'Under 5,000 km',
  },
  {
    id: 'car12',
    make: 'Audi',
    model: 'A4',
    year: 2023,
    price: {
      new: 40000,
      used_1_year: 37000,
      used_3_year: 32000,
      used_5_year: 26000,
    },
    fuelType: ['Gasoline'],
    bodyStyle: ['Sedan'],
    demographics: {
      gender: ['Male', 'Female'],
      ageGroup: ['35-44', '45-54'],
      drivingExperience: ['Experienced', 'Veteran'],
    },
    locationType: ['Suburban', 'Urban/City'],
    features: ['Quattro AWD', 'Virtual Cockpit'],
    performance: 'Sporty & Agile',
    cargoNeeds: 'Moderate',
    passengers: '1-2',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car13',
    make: 'Kia',
    model: 'Sorento',
    year: 2023,
    price: {
      new: 34000,
      used_1_year: 31000,
      used_3_year: 27000,
      used_5_year: 21000,
    },
    fuelType: ['LPG/GPL', 'Gasoline'],
    bodyStyle: ['SUV/Crossover'],
    demographics: {
      gender: ['Female', 'Non-binary'],
      ageGroup: ['35-44', '45-54'],
      drivingExperience: ['Experienced', 'Veteran'],
    },
    locationType: ['Suburban', 'Rural'],
    features: ['7-Seater', 'Panoramic Sunroof'],
    performance: 'Smooth & Comfortable',
    cargoNeeds: 'Significant',
    passengers: '5+',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car14',
    make: 'Toyota',
    model: 'Mirai',
    year: 2023,
    price: {
      new: 50000,
      used_1_year: 47000,
      used_3_year: 42000,
      used_5_year: 35000,
    },
    fuelType: ['Hydrogen Fuel Cell (FCEV)'],
    bodyStyle: ['Sedan'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['35-44', '45-54'],
      drivingExperience: ['Experienced', 'Veteran'],
    },
    locationType: ['Urban/City', 'Suburban'],
    features: ['Advanced Technology', 'Eco-friendly'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Minimal',
    passengers: '1-2',
    annualMileage: '5,000 - 15,000 km',
  },
  {
    id: 'car15',
    make: 'Mazda',
    model: 'CX-5',
    year: 2023,
    price: {
      new: 29000,
      used_1_year: 27000,
      used_3_year: 23000,
      used_5_year: 19000,
    },
    fuelType: ['Gasoline'],
    bodyStyle: ['SUV/Crossover'],
    demographics: {
      gender: ['Female', 'Non-binary'],
      ageGroup: ['25-34', '35-44'],
      drivingExperience: ['Experienced'],
    },
    locationType: ['Suburban', 'Urban/City'],
    features: ['AWD', 'Premium Interior'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Moderate',
    passengers: '3-4',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car16',
    make: 'Renault',
    model: 'Laguna 2',
    year: 2006,
    price: {
      used_10_year: 3000,
      used_15_year: 2000,
      used_20_year: 1500,
    },
    fuelType: ['Diesel', 'Gasoline'],
    bodyStyle: ['Sedan', 'Wagon'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['18-24', '25-34', '35-44', '45-54', '55-64', '65+'],
      drivingExperience: ['Novice', 'Experienced', 'Veteran'],
    },
    locationType: ['Urban/City', 'Suburban', 'Rural', 'Mixed'],
    features: ['Comfortable Ride', 'Spacious Interior'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Moderate',
    passengers: '3-4',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car17',
    make: 'BMW',
    model: 'X5',
    year: 2020,
    price: {
      new: 60000,
      used_1_year: 55000,
      used_3_year: 48000,
      used_5_year: 40000,
    },
    fuelType: ['Gasoline', 'Plug-in Hybrid (PHEV)'],
    bodyStyle: ['SUV/Crossover'],
    demographics: {
      gender: ['Male', 'Female'],
      ageGroup: ['35-44', '45-54', '55-64'],
      drivingExperience: ['Experienced', 'Veteran'],
    },
    locationType: ['Suburban', 'Mixed'],
    features: ['Luxury Interior', 'AWD', 'Advanced Safety'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Significant',
    passengers: '5+',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car18',
    make: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2018,
    price: {
      new: 55000,
      used_1_year: 48000,
      used_3_year: 40000,
      used_5_year: 32000,
    },
    fuelType: ['Diesel', 'Gasoline'],
    bodyStyle: ['Sedan', 'Wagon'],
    demographics: {
      gender: ['Male', 'Female'],
      ageGroup: ['45-54', '55-64', '65+'],
      drivingExperience: ['Veteran'],
    },
    locationType: ['Urban/City', 'Suburban'],
    features: ['Luxury Interior', 'Comfortable Ride', 'Advanced Safety'],
    performance: 'Smooth & Comfortable',
    cargoNeeds: 'Moderate',
    passengers: '1-2',
    annualMileage: '5,000 - 15,000 km',
  },
  {
    id: 'car19',
    make: 'Toyota',
    model: 'Prius',
    year: 2015,
    price: {
      new: 25000,
      used_1_year: 22000,
      used_3_year: 18000,
      used_5_year: 14000,
      used_10_year: 9000,
    },
    fuelType: ['Full Hybrid (HEV)'],
    bodyStyle: ['Hatchback'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['25-34', '35-44', '45-54'],
      drivingExperience: ['Experienced'],
    },
    locationType: ['Urban/City', 'Suburban'],
    features: ['Fuel-efficient', 'Reliable'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Moderate',
    passengers: '3-4',
    annualMileage: '15,000 - 30,000 km',
  },
  {
    id: 'car20',
    make: 'Dacia',
    model: 'Duster',
    year: 2022,
    price: {
      new: 18000,
      used_1_year: 16000,
      used_3_year: 13000,
    },
    fuelType: ['Gasoline', 'LPG/GPL', 'Diesel'],
    bodyStyle: ['SUV/Crossover'],
    demographics: {
      gender: ['Male', 'Female', 'Non-binary'],
      ageGroup: ['25-34', '35-44', '45-54'],
      drivingExperience: ['Novice', 'Experienced'],
    },
    locationType: ['Rural', 'Mixed'],
    features: ['Affordable', 'Rugged', 'High Ground Clearance'],
    performance: 'Balanced Performance',
    cargoNeeds: 'Significant',
    passengers: '3-4',
    annualMileage: '15,000 - 30,000 km',
  },
];

export default carDatabase;
